# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!


target ‘AFKitDemo’ do

pod 'AFNetworking', '~> 3.0’

pod 'SVProgressHUD’

pod 'MBProgressHUD'

pod 'MJRefresh'

pod 'FCUUID'

pod 'Masonry'


end

